ALTER TABLE "invoices"
ADD COLUMN "roundOffAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "applyRoundOff" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "purchase_invoices"
ADD COLUMN "roundOffAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "applyRoundOff" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "debit_notes"
ADD COLUMN "roundOffAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "applyRoundOff" BOOLEAN NOT NULL DEFAULT false;
